# Generated by Django 5.2.1 on 2025-05-19 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='read_articles',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='ArticleInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('vote', models.SmallIntegerField(blank=True, choices=[(1, 'Like'), (-1, 'Dislike')], null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.article')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.userprofile')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('user_profile', 'article')},
            },
        ),
    ]
